server:
  port: 9202
spring:
  application:
    name: task
  rabbitmq:
    host: 127.0.0.1
  kafka:
    bootstrap-servers: 192.168.200.129:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

