server:
  port: 8001
spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #认证微服务
        - id: draw_oauth
          uri: lb://user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        #抽奖服务
        - id: draw_infos
          uri: lb://info
          predicates:
            - Path=/api/info/**
          filters:
            - StripPrefix=1
        #用户服务
        - id: draw_user
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        #参加抽奖
        - id: draw_join
          uri: lb://join
          predicates:
            - Path=/api/join/**
          filters:
            - StripPrefix=1





eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true